name:                hs-cmake
version:             0.1.0.0
github:              "AeroStun/hs-cmake"
license:             Apache-2.0
author:              "AeroStun"
maintainer:          "AeroStun"
copyright:           "2021 AeroStun"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            CMake script mode interpreter
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AeroStun/hs-cmake>

dependencies:
- base >= 4.7 && < 5
- base16-bytestring
- bytestring
- case-insensitive
- containers
- directory
- either
- extra
- filepath
- monad-loops
- mtl
- parsers
- prettyprinter
- stringsearch
- transformers
- trifecta
- unordered-containers

library:
  source-dirs: src

executables:
  hs-cmake-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-cmake

tests:
  hs-cmake-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hs-cmake
    - stringsearch
    - QuickCheck
    - quickcheck-instances
